// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbR9cR8SoScEXYlNl0drwFNutYw3-OKrU',
    appId: '1:596477561885:web:b865d1e87206749ab54af4',
    messagingSenderId: '596477561885',
    projectId: 'parmesan-6cfe6',
    authDomain: 'parmesan-6cfe6.firebaseapp.com',
    storageBucket: 'parmesan-6cfe6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDemsNTLnIaF4YW3Fwvag_C2vw2axLVxjc',
    appId: '1:596477561885:android:72e194ef71d1dee7b54af4',
    messagingSenderId: '596477561885',
    projectId: 'parmesan-6cfe6',
    storageBucket: 'parmesan-6cfe6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCppKpkPikzzVWcZd_65W7rNYe6rD8TzOU',
    appId: '1:596477561885:ios:1456589f7312daddb54af4',
    messagingSenderId: '596477561885',
    projectId: 'parmesan-6cfe6',
    storageBucket: 'parmesan-6cfe6.appspot.com',
    iosBundleId: 'com.example.mobileParmesan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCppKpkPikzzVWcZd_65W7rNYe6rD8TzOU',
    appId: '1:596477561885:ios:47d11e79ed90bd9fb54af4',
    messagingSenderId: '596477561885',
    projectId: 'parmesan-6cfe6',
    storageBucket: 'parmesan-6cfe6.appspot.com',
    iosBundleId: 'com.example.mobileParmesan.RunnerTests',
  );
}
